In [10]:
import numpy as np
# from keras.models import Model
# from keras.layers import Input, Dense, Dropout
# from keras.utils import to_categorical
from sklearn.model_selection import train_test_split
# from keras.callbacks import EarlyStopping

from keras.utils.np_utils import to_categorical
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.models import Sequential, load_model
from keras.datasets import mnist
import itertools
import random

# Create an input array of 50,000 samples of 20 random numbers each
x = np.random.randint(0, 100, size=(50000, 10))

# And a one-hot encoded target denoting the index of the maximum of the inputs
y = to_categorical(np.argmax(x, axis=1), num_classes=10)

# Split into training and testing datasets
x_train, x_test, y_train, y_test = train_test_split(x, y)



In [11]:
x_train.shape

(37500, 10)

In [12]:
y_train.shape

(37500, 10)

In [16]:
# Build a network, probaly needlessly complicated since it needs a lot of dropout to
# perform even reasonably well.

# i = layers.Input(shape=(20, ))
# a = layers.Dense(1024, activation='relu')(i)
# b = layers.Dense(512, activation='relu')(a)
# ba = layers.Dropout(0.3)(b)
# c = layers.Dense(256, activation='relu')(ba)
# d = layers.Dense(128, activation='relu')(c)
# o = layers.Dense(20, activation='softmax')(d)

# Convolutional NN
model = tf.keras.Sequential()
model.add(layers.Dense(512, activation = 'relu', input_shape=(10,)))
model.add(layers.Dense(10, activation='softmax'))



# model = Model(inputs=i, outputs=o)

# es = EarlyStopping(monitor='val_loss', patience=3)

model.compile(optimizer='rmsprop', loss='categorical_crossentropy', metrics = ['accuracy', 'mae'])

model.fit(x_train, y_train, epochs=30, batch_size=8)

print(np.where(np.argmax(model.predict(x_test), axis=1) == np.argmax(y_test, axis=1), 1, 0).mean())

Epoch 1/30
4688/4688 [==============================] - 3s 576us/step - loss: 0.9133 - accuracy: 0.7573 - mae: 0.0513
Epoch 2/30
4688/4688 [==============================] - 3s 555us/step - loss: 0.6315 - accuracy: 0.8202 - mae: 0.0381
Epoch 3/30
4688/4688 [==============================] - 3s 559us/step - loss: 0.5892 - accuracy: 0.8377 - mae: 0.0345
Epoch 4/30
4688/4688 [==============================] - 2s 521us/step - loss: 0.5901 - accuracy: 0.8456 - mae: 0.0327
Epoch 5/30
4688/4688 [==============================] - 2s 511us/step - loss: 0.5768 - accuracy: 0.8526 - mae: 0.0310
Epoch 6/30
4688/4688 [==============================] - 2s 505us/step - loss: 0.5566 - accuracy: 0.8573 - mae: 0.0298
Epoch 7/30
4688/4688 [==============================] - 2s 523us/step - loss: 0.5599 - accuracy: 0.8648 - mae: 0.0283
Epoch 8/30
4688/4688 [==============================] - 3s 558us/step - loss: 0.5483 - accuracy: 0.8668 - mae: 0.0276
Epoch 9/30
4688/4688 [==============================] - 

In [17]:
eval_model = model.evaluate(x_test, y_test)

391/391 [==============================] - 0s 460us/step - loss: 0.4060 - accuracy: 0.9110 - mae: 0.0182


In [48]:
list_A = []
list_B = []
list_2D = []

list_label = []

num_iterations = 50000

for i in range(num_iterations):
    
    num_A = random.randint(0,9)
    num_B = random.randint(0,9)
    
    list_2D.append([min(num_A,num_B), max(num_A,num_B)])
    
    label = min(num_A,num_B)
    list_label.append(label)
    

In [76]:
val_list_A = []
val_list_B = []
val_list_2D = []

val_list_label = []

num_iterations = 50000

for i in range(num_iterations):
    
    num_A = random.randint(0,9)
    num_B = random.randint(0,9)
    
    val_list_2D.append([max(num_A,num_B), min(num_A,num_B)])
    
    label = min(num_A,num_B)
    val_list_label.append(label)

In [78]:
val_list_2D.shape

(50000, 2)

In [49]:
list_label[:5]

[0, 4, 0, 3, 0]

In [ ]:
list_2D

In [75]:
list_2D.shape

(50000, 2)

In [51]:
np.unique(list_label)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
np.unique(list_label)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [77]:
list_2D = np.array(list_2D)
list_label = to_categorical(np.array(list_label))

val_list_2D = np.array(val_list_2D)
val_list_label = to_categorical(np.array(val_list_label))

In [67]:
val_list_2D.shape

(50000, 2, 10)

In [69]:
val_list_label.shape

(50000, 10)

In [72]:
val_list_label[:5]

array([[0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.]])

In [73]:
val_list_2D.shape

(50000, 2, 10)

In [54]:
list_label[:5]

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [55]:
list_2D[:5]

array([[0, 8],
       [4, 5],
       [0, 8],
       [3, 8],
       [0, 0]])

In [ ]:
model = tf.keras.Sequential()
model.add(layers.Dense(512, activation = 'relu', input_shape=(2,)))
model.add(layers.Dense(10, activation='softmax'))

model.compile(optimizer='rmsprop', loss='categorical_crossentropy', metrics = ['accuracy', 'mae'])

model.fit(list_2D, list_label, epochs=4, batch_size=1)

#print(np.where(np.argmax(model.predict(x_test), axis=1) == np.argmax(y_test, axis=1), 1, 0).mean())

In [79]:
eval_model = model.evaluate(val_list_2D, val_list_label)

1563/1563 [==============================] - 1s 639us/step - loss: 158.2463 - accuracy: 0.0974 - mae: 0.1805
